// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service03.proto

package grpc.project.distributedSys;

public interface BlockAccessMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlockAccessMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>bool secure_flag = 2;</code>
   */
  boolean getSecureFlag();
}
