// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service02.proto

package grpc.project.distributedSys;

public interface RequestTwoFAMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestTwoFAMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
