// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service01.proto

package grpc.project.distributedSys;

public interface RequestSecProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestSecProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();
}
