// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service01.proto

package grpc.project.distributedSys;

public interface RequestDoorAccessMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestDoorAccessMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string door_id = 1;</code>
   */
  java.lang.String getDoorId();
  /**
   * <code>string door_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoorIdBytes();

  /**
   * <code>string pin = 2;</code>
   */
  java.lang.String getPin();
  /**
   * <code>string pin = 2;</code>
   */
  com.google.protobuf.ByteString
      getPinBytes();
}
