// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service01.proto

package grpc.project.distributedSys;

public interface ResponseAccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseAccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_response = 1;</code>
   */
  java.lang.String getAccessResponse();
  /**
   * <code>string access_response = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessResponseBytes();
}
