// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service02.proto

package grpc.project.distributedSys;

public final class Service02Impl {
  private Service02Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetSecurityProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetSecurityProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetSecurityProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetSecurityProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerifyPreApprovalMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerifyPreApprovalMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerifyPreApprovalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerifyPreApprovalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestTwoFAMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestTwoFAMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestTwoFAResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestTwoFAResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Service02.proto\"r\n\031SetSecurityProfileR" +
      "equest\022\017\n\007user_id\030\001 \001(\t\022\026\n\016security_leve" +
      "l\030\002 \001(\t\022\023\n\013secure_flag\030\003 \001(\010\022\027\n\017employme" +
      "nt_type\030\004 \001(\t\"p\n\032SetSecurityProfileRespo" +
      "nse\022\017\n\007user_id\030\001 \001(\t\022\026\n\016security_level\030\002" +
      " \001(\t\022\027\n\017two_factor_auth\030\003 \001(\010\022\020\n\010date_se" +
      "t\030\004 \001(\t\"\'\n\024VerifyPreApprovalMsg\022\017\n\007user_" +
      "id\030\001 \001(\t\"+\n\031VerifyPreApprovalResponse\022\016\n" +
      "\006result\030\001 \001(\t\"\"\n\017RequestTwoFAMsg\022\017\n\007user" +
      "_id\030\001 \001(\t\"&\n\024RequestTwoFAResponse\022\016\n\006res" +
      "ult\030\001 \001(\t2\347\001\n\rAccessControl\022Q\n\022SetSecuri" +
      "tyProfile\022\032.SetSecurityProfileRequest\032\033." +
      "SetSecurityProfileResponse\"\0000\001\022H\n\021Verify" +
      "PreApproval\022\025.VerifyPreApprovalMsg\032\032.Ver" +
      "ifyPreApprovalResponse\"\000\0229\n\014RequestTwoFA" +
      "\022\020.RequestTwoFAMsg\032\025.RequestTwoFARespons" +
      "e\"\000B.\n\033grpc.project.distributedSysB\rServ" +
      "ice02ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SetSecurityProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SetSecurityProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetSecurityProfileRequest_descriptor,
        new java.lang.String[] { "UserId", "SecurityLevel", "SecureFlag", "EmploymentType", });
    internal_static_SetSecurityProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SetSecurityProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetSecurityProfileResponse_descriptor,
        new java.lang.String[] { "UserId", "SecurityLevel", "TwoFactorAuth", "DateSet", });
    internal_static_VerifyPreApprovalMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VerifyPreApprovalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerifyPreApprovalMsg_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_VerifyPreApprovalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_VerifyPreApprovalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerifyPreApprovalResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_RequestTwoFAMsg_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RequestTwoFAMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestTwoFAMsg_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_RequestTwoFAResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RequestTwoFAResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestTwoFAResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
