// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service01.proto

package grpc.project.distributedSys;

public final class Service01Impl {
  private Service01Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestRFIDMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestRFIDMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestDoorAccessMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestDoorAccessMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseAccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestSecProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestSecProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecurityProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecurityProfile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Service01.proto\"\036\n\016RequestRFIDMsg\022\014\n\004c" +
      "ode\030\001 \001(\t\"4\n\024RequestDoorAccessMsg\022\017\n\007doo" +
      "r_id\030\001 \001(\t\022\013\n\003pin\030\002 \001(\t\")\n\016ResponseAcces" +
      "s\022\027\n\017access_response\030\001 \001(\t\"#\n\021RequestSec" +
      "Profile\022\016\n\006userId\030\001 \001(\005\"\205\001\n\017SecurityProf" +
      "ile\022\026\n\016security_level\030\001 \001(\t\022\023\n\013secure_fl" +
      "ag\030\002 \001(\010\022\027\n\017two_factor_auth\030\003 \001(\010\022\027\n\017emp" +
      "loyment_type\030\004 \001(\t\022\023\n\013access_date\030\005 \001(\t2" +
      "\320\001\n\026SecurityRequestService\0223\n\013RequestRFI" +
      "D\022\017.RequestRFIDMsg\032\017.ResponseAccess\"\000(\001\022" +
      "?\n\021RequestDoorAccess\022\025.RequestDoorAccess" +
      "Msg\032\017.ResponseAccess\"\000(\001\022@\n\026RequestSecur" +
      "ityProfile\022\022.RequestSecProfile\032\020.Securit" +
      "yProfile\"\000B.\n\033grpc.project.distributedSy" +
      "sB\rService01ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestRFIDMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestRFIDMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestRFIDMsg_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_RequestDoorAccessMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestDoorAccessMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestDoorAccessMsg_descriptor,
        new java.lang.String[] { "DoorId", "Pin", });
    internal_static_ResponseAccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseAccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseAccess_descriptor,
        new java.lang.String[] { "AccessResponse", });
    internal_static_RequestSecProfile_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestSecProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestSecProfile_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_SecurityProfile_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SecurityProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecurityProfile_descriptor,
        new java.lang.String[] { "SecurityLevel", "SecureFlag", "TwoFactorAuth", "EmploymentType", "AccessDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
