// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service02.proto

package grpc.project.distributedSys;

public interface SetSecurityProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetSecurityProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string security_level = 2;</code>
   */
  java.lang.String getSecurityLevel();
  /**
   * <code>string security_level = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecurityLevelBytes();

  /**
   * <code>bool secure_flag = 3;</code>
   */
  boolean getSecureFlag();

  /**
   * <code>string employment_type = 4;</code>
   */
  java.lang.String getEmploymentType();
  /**
   * <code>string employment_type = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();
}
