// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service03.proto

package grpc.project.distributedSys;

public interface SuggestIncidentResponseMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SuggestIncidentResponseMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key_id = 1;</code>
   */
  java.lang.String getKeyId();
  /**
   * <code>string key_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyIdBytes();

  /**
   * <code>string response = 2;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
