// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service03.proto

package grpc.project.distributedSys;

public interface SuggestIncidentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SuggestIncidentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_fail_condition_trips = 1;</code>
   */
  java.lang.String getAccessFailConditionTrips();
  /**
   * <code>string access_fail_condition_trips = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessFailConditionTripsBytes();
}
