// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service03.proto

package grpc.project.distributedSys;

/**
 * Protobuf type {@code SuggestIncidentRequest}
 */
public  final class SuggestIncidentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SuggestIncidentRequest)
    SuggestIncidentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SuggestIncidentRequest.newBuilder() to construct.
  private SuggestIncidentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SuggestIncidentRequest() {
    accessFailConditionTrips_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SuggestIncidentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accessFailConditionTrips_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.project.distributedSys.Service03Impl.internal_static_SuggestIncidentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.project.distributedSys.Service03Impl.internal_static_SuggestIncidentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.project.distributedSys.SuggestIncidentRequest.class, grpc.project.distributedSys.SuggestIncidentRequest.Builder.class);
  }

  public static final int ACCESS_FAIL_CONDITION_TRIPS_FIELD_NUMBER = 1;
  private volatile java.lang.Object accessFailConditionTrips_;
  /**
   * <code>string access_fail_condition_trips = 1;</code>
   */
  public java.lang.String getAccessFailConditionTrips() {
    java.lang.Object ref = accessFailConditionTrips_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessFailConditionTrips_ = s;
      return s;
    }
  }
  /**
   * <code>string access_fail_condition_trips = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccessFailConditionTripsBytes() {
    java.lang.Object ref = accessFailConditionTrips_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessFailConditionTrips_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccessFailConditionTripsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessFailConditionTrips_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccessFailConditionTripsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessFailConditionTrips_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.project.distributedSys.SuggestIncidentRequest)) {
      return super.equals(obj);
    }
    grpc.project.distributedSys.SuggestIncidentRequest other = (grpc.project.distributedSys.SuggestIncidentRequest) obj;

    boolean result = true;
    result = result && getAccessFailConditionTrips()
        .equals(other.getAccessFailConditionTrips());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCESS_FAIL_CONDITION_TRIPS_FIELD_NUMBER;
    hash = (53 * hash) + getAccessFailConditionTrips().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.project.distributedSys.SuggestIncidentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.project.distributedSys.SuggestIncidentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SuggestIncidentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SuggestIncidentRequest)
      grpc.project.distributedSys.SuggestIncidentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.project.distributedSys.Service03Impl.internal_static_SuggestIncidentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.project.distributedSys.Service03Impl.internal_static_SuggestIncidentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.project.distributedSys.SuggestIncidentRequest.class, grpc.project.distributedSys.SuggestIncidentRequest.Builder.class);
    }

    // Construct using grpc.project.distributedSys.SuggestIncidentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accessFailConditionTrips_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.project.distributedSys.Service03Impl.internal_static_SuggestIncidentRequest_descriptor;
    }

    @java.lang.Override
    public grpc.project.distributedSys.SuggestIncidentRequest getDefaultInstanceForType() {
      return grpc.project.distributedSys.SuggestIncidentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.project.distributedSys.SuggestIncidentRequest build() {
      grpc.project.distributedSys.SuggestIncidentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.project.distributedSys.SuggestIncidentRequest buildPartial() {
      grpc.project.distributedSys.SuggestIncidentRequest result = new grpc.project.distributedSys.SuggestIncidentRequest(this);
      result.accessFailConditionTrips_ = accessFailConditionTrips_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.project.distributedSys.SuggestIncidentRequest) {
        return mergeFrom((grpc.project.distributedSys.SuggestIncidentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.project.distributedSys.SuggestIncidentRequest other) {
      if (other == grpc.project.distributedSys.SuggestIncidentRequest.getDefaultInstance()) return this;
      if (!other.getAccessFailConditionTrips().isEmpty()) {
        accessFailConditionTrips_ = other.accessFailConditionTrips_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.project.distributedSys.SuggestIncidentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.project.distributedSys.SuggestIncidentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accessFailConditionTrips_ = "";
    /**
     * <code>string access_fail_condition_trips = 1;</code>
     */
    public java.lang.String getAccessFailConditionTrips() {
      java.lang.Object ref = accessFailConditionTrips_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessFailConditionTrips_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string access_fail_condition_trips = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccessFailConditionTripsBytes() {
      java.lang.Object ref = accessFailConditionTrips_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessFailConditionTrips_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string access_fail_condition_trips = 1;</code>
     */
    public Builder setAccessFailConditionTrips(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessFailConditionTrips_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string access_fail_condition_trips = 1;</code>
     */
    public Builder clearAccessFailConditionTrips() {
      
      accessFailConditionTrips_ = getDefaultInstance().getAccessFailConditionTrips();
      onChanged();
      return this;
    }
    /**
     * <code>string access_fail_condition_trips = 1;</code>
     */
    public Builder setAccessFailConditionTripsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessFailConditionTrips_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SuggestIncidentRequest)
  }

  // @@protoc_insertion_point(class_scope:SuggestIncidentRequest)
  private static final grpc.project.distributedSys.SuggestIncidentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.project.distributedSys.SuggestIncidentRequest();
  }

  public static grpc.project.distributedSys.SuggestIncidentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SuggestIncidentRequest>
      PARSER = new com.google.protobuf.AbstractParser<SuggestIncidentRequest>() {
    @java.lang.Override
    public SuggestIncidentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SuggestIncidentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SuggestIncidentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SuggestIncidentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.project.distributedSys.SuggestIncidentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

